In [ ]:
import pandas as pd
import numpy as np

df=pd.DataFrame(np.arange(1,101).reshape((5,20)))
print(df)
rows = np.array(df[((df > 20) & (df < 50)).all(axis=1)]).reshape((4,5))
data=pd.DataFrame(rows)
data

   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
1  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
2  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59
3  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
4  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99

    19
0   20
1   40
2   60
3   80
4  100

    0   1   2   3   4
0  21  22  23  24  25
1  26  27  28  29  30
2  31  32  33  34  35
3  36  37  38  39  40

In [ ]:
data[(data % 7 ==0).any()]

C:\Users\Dipak\AppData\Local\Temp\ipykernel_14528\930032474.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[(data % 7 ==0).any()]

    0   1   2   3   4
0  21  22  23  24  25
2  31  32  33  34  35

In [ ]:
import statsmodels.api as sm
# Load the same macrodata dataset used in the book
data = sm.datasets.macrodata.load_pandas().data

data.head()

In [ ]:
import statsmodels.api as sm
print(sm.__version__)