In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_excel('real.xlsx')
df.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
0,2025-0750-AFG,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2025-000153,NaN,AFG,...,NaN,NaN,NaN,180000.0,180000.0,100.0,NaN,NaN,2025-09-01,2026-05-15
1,2026-0305-AFG,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,AFG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-05-04,2026-05-11
2,2026-0174-SYR,No,nat-met-sto-sev,Natural,Meteorological,Storm,Severe weather,NaN,NaN,SYR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-18,2026-05-15
3,2025-0272-KGZ,No,nat-bio-epi-vir,Natural,Biological,Epidemic,Viral disease,GLIDE:EP-2025-000030|GLIDE:EP-2025-000105,Measles & Rubella,KGZ,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,2025-04-16,2026-05-20
4,2026-0227-BGD,No,nat-bio-epi-vir,Natural,Biological,Epidemic,Viral disease,GLIDE:EP-2026-000048,Meales,BGD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-07,2026-05-20

In [8]:
# df.info()
# df.isnull().sum()
# df.duplicated().sum()

In [9]:
# df['Disaster Type'].value_counts()
df['Country'].value_counts().head(10)

Country
China          643
India          410
Indonesia      409
Philippines    389
Viet Nam       196
Afghanistan    177
Japan          177
Pakistan       169
Bangladesh     145
Thailand       130
Name: count, dtype: int64

In [10]:
df.columns

Index(['DisNo.', 'Historic', 'Classification Key', 'Disaster Group',
       'Disaster Subgroup', 'Disaster Type', 'Disaster Subtype',
       'External IDs', 'Event Name', 'ISO', 'Country', 'Subregion', 'Region',
       'Location', 'Origin', 'Associated Types', 'OFDA/BHA Response', 'Appeal',
       'Declaration', 'AID Contribution ('000 US$)', 'Magnitude',
       'Magnitude Scale', 'Latitude', 'Longitude', 'River Basin', 'Start Year',
       'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day',
       'Total Deaths', 'No. Injured', 'No. Affected', 'No. Homeless',
       'Total Affected', 'Reconstruction Costs ('000 US$)',
       'Reconstruction Costs, Adjusted ('000 US$)',
       'Insured Damage ('000 US$)', 'Insured Damage, Adjusted ('000 US$)',
       'Total Damage ('000 US$)', 'Total Damage, Adjusted ('000 US$)', 'CPI',
       'Admin Units', 'GADM Admin Units', 'Entry Date', 'Last Update'],
      dtype='str')

In [11]:
df['Disaster Subgroup'].unique()

<StringArray>
['Geophysical', 'Hydrological', 'Meteorological', 'Biological',
 'Climatological']
Length: 5, dtype: str

In [12]:
df.groupby('year').size().plot(kind='line')

KeyError: 'year'

In [ ]:
df1=df[df['Disaster Subgroup']=='Geophysical']

In [ ]:
df2=df1[df1['Disaster Type']=='Earthquake']

In [ ]:
df3=df1[df1['ISO']=='IND']
df3

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
347,2015-0476-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2015-000147|USGS:us10003re5,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,73.620803,"[{""adm1_code"":1489,""adm1_name"":""Delhi""},{""adm1...","[{""gid_1"":""IND.25_1"",""migration_date"":""2025-12...",2015-10-28,2025-12-20
1098,2011-0351-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2011-000136|USGS:usp000j88b,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,69.869264,"[{""adm1_code"":1487,""adm1_name"":""Assam""},{""adm1...","[{""gid_1"":""IND.22_1"",""migration_date"":""2025-12...",2011-11-07,2025-12-20
1180,2001-0033-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp000a8ds,NaN,IND,...,NaN,100000.0,181820.0,2623000.0,4769144.0,54.999385,"[{""adm2_code"":17635,""adm2_name"":""Ahmadabad""},{...","[{""gid_2"":""IND.11.10_1"",""migration_date"":""2025...",2014-04-04,2025-12-20
1254,2002-0584-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp000bc65,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,55.871696,"[{""adm2_code"":17545,""adm2_name"":""Andaman Islan...","[{""gid_2"":""IND.1.2_1"",""migration_date"":""2025-1...",2005-06-27,2025-12-20
2312,2004-0659-IND,No,nat-geo-ear-tsu,Natural,Geophysical,Earthquake,Tsunami,GLIDE:TS-2004-000147|USGS:official200412260058...,NaN,IND,...,NaN,5000.0,8522.0,1022800.0,1743316.0,58.669809,"[{""adm1_code"":1484,""adm1_name"":""Andaman and Ni...","[{""gid_1"":""IND.1_1"",""migration_date"":""2025-12-...",2014-03-27,2026-01-25
2708,2015-0175-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:us20002ejl,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,73.620803,"[{""adm1_code"":70073,""adm1_name"":""Bihar""}]","[{""gid_1"":""IND.5_1"",""migration_date"":""2025-12-...",2015-05-21,2025-12-20
2945,2021-0225-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,84.166983,"[{""adm2_code"":17593,""adm2_name"":""Sonitpur""}]","[{""gid_2"":""IND.4.25_1"",""migration_date"":""2025-...",2021-04-29,2025-12-20
3461,2005-0575-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2005-000174|USGS:usp000e12e,NaN,IND,...,NaN,NaN,NaN,1000000.0,1648524.0,60.660332,"[{""adm2_code"":40410,""adm2_name"":""Administrativ...",NaN,2014-03-26,2025-06-25
3706,2012-0049-IND,No,nat-geo-mmd-ava,Natural,Geophysical,Mass movement (dry),Avalanche (dry),NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,71.315088,"[{""adm2_code"":72794,""adm2_name"":""Administrativ...",NaN,2013-02-04,2023-09-25
3737,2013-0140-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2013-000056|USGS:usb000gjhz,NaN,IND,...,NaN,NaN,NaN,120000.0,165838.0,72.359737,"[{""adm2_code"":72809,""adm2_name"":""Administrativ...",NaN,2013-07-05,2023-09-25
3844,2015-0144-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2015-000048|USGS:us20002926,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,73.620803,"[{""adm1_code"":1507,""adm1_name"":""Sikkim""},{""adm...","[{""gid_1"":""IND.30_1"",""migration_date"":""2025-12...",2015-04-28,2025-12-20
3872,2016-0002-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2016-000001|USGS:us10004b2n,NaN,IND,...,NaN,NaN,NaN,75000.0,100604.0,74.549603,"[{""adm2_code"":17583,""adm2_name"":""Kamrup""},{""ad...","[{""gid_2"":""IND.21.1_1"",""migration_date"":""2025-...",2016-01-12,2026-01-25