## Binary Data Formats

'''Python DataFrame
        │
        ▼
   Binary Format
 (pickle/parquet)
        │
 Save to Disk
        │
        ▼
Binary File
        │
Later...
        │
        ▼
Read Binary File
        │
        ▼
Same DataFrame'''

### Pickle is Python's built-in module that converts any Python object into binary data so it can be stored on disk and later restored exactly as it was.

'''Python Object
      │
 Serialize
      ▼
Binary File (.pkl)
      │
 Deserialize
      ▼
Same Python Object'''

- Serialization → Object ➜ Binary file
- Deserialization → Binary file ➜ Object

In [12]:
import pandas as pd
import numpy as np
import pickle
frame=pd.read_csv("examples/ex1.csv")
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [13]:
frame.to_pickle('examples/frame_pickle')

In [14]:
pd.read_pickle('examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [15]:
df = pd.DataFrame({
    "Name":["Deep","Rahul","Aman"],
    "CGPA":[8.47,8.45,9.10]
})

with open("examples/students.pkl","wb") as f:
    pickle.dump(df,f)

In [16]:
with open("examples/students.pkl","rb") as f:
    df2 = pickle.load(f)

df2

    Name  CGPA
0   Deep  8.47
1  Rahul  8.45
2   Aman  9.10

## Using HDF5 Format

In [17]:

frame = pd.DataFrame({'a': np.random.standard_normal(100)})
store = pd.HDFStore('mydata.h5')

In [18]:
store

<class 'pandas.HDFStore'>
File path: mydata.h5

In [19]:
store['obj1'] = frame
store['obj1_col'] = frame['a']
store['obj1']

           a
0  -1.165723
1   1.137916
2   0.667454
3  -1.362799
4  -1.286260
..       ...
95 -1.033200
96  2.467060
97  0.220924
98 -1.001028
99  0.151281

[100 rows x 1 columns]

In [20]:
store.put("obj2", frame, format="table")
store.select('obj2',where=['index>=10 and index<=15'])

           a
10 -0.461565
11  1.538282
12 -0.411474
13  0.655592
14 -1.071075
15  0.039918

In [21]:
store.close()

In [22]:
frame.to_hdf('mydata.h5',key='obj',format='table')

In [23]:
pd.read_hdf('mydata.h5',key='obj',where=['index < 5'])

          a
0 -1.165723
1  1.137916
2  0.667454
3 -1.362799
4 -1.286260

##  Reading MS Excel Files

In [24]:
xlsx = pd.ExcelFile('examples/ex_excel.xlsx')
xlsx.sheet_names

['Sheet1']

In [25]:
pd.read_excel(xlsx,'Sheet1')
# we can also pass file name instead of xlsx

      name  age    city
0    Alice   25  Mumbai
1      Bob   30   Delhi
2  Charlie   35    Pune

## Interacting with WebAPIs

Web API
   │
HTTP GET request
   │
JSON response
   │
Python (requests)
   │
Pandas DataFrame

In [26]:
import requests
url='https://api.github.com/repos/pandas-dev/pandas/issues'
resp=requests.get(url)
resp

In [27]:
data=resp.json()
data[0]['title']

'BUG: assert_series_equal atol not respected for large integers due to float64 cast (#66400)'

In [28]:
issues=pd.DataFrame(data,columns=['number','title','labels','state'])
issues

,number,title,labels,state
0,66424,BUG: assert_series_equal atol not respected fo...,[],open
1,66423,BUG: str.split() on ArrowDtype keeps empty whi...,[],open
2,66422,BUG: fix ASCII (re.A) flag being overridden by...,[],open
3,66421,Update doc styler na rep,[],open
4,66420,ENH: Ability to specify locale in Datetime and...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
5,66419,TST: check data file existence instead of dire...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
6,66418,BLD: honor numpy-include-dir meson property wh...,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
7,66417,BLD: invoke generate_version.py through the in...,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
8,66416,BLD: build window extensions against strict C+...,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
9,66410,BUG: Cannot build `pandas` with MSVC,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
10,66409,PERF: avoid pearson correlation L3 cache regre...,[],open
11,66408,BUG: fix mask order mismatch with values for n...,[],open
12,66407,BUG: styler.format.na_rep not respected inside...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
13,66406,BUG: Rewrite handling for flags and case,[],open
14,66405,BUG: assert_almost_equal not respecting atol/r...,[],open
15,66404,BUG: merge on NaN-labeled join key produced du...,[],open
16,66400,BUG: pd.testing.assert_series_equal not respec...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
17,66399,BUG: DataFrame constructor from unique integer...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,66397,DOC: batch of documentation clarifications,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
19,66396,DOC: Clarify limit keyword behavior in interpo...,[],open
20,66395,DOC: Fix unescaped \right in DataFrame.ewm hal...,[],open
21,66393,bug fix for #66390,[],open
22,66391,ENH: UnicodeDecodeError from read_csv could su...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
23,66390,BUG: ArrowDtype timestamp comparison with date...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
24,66389,ENH: Support `tz_convert` on naive timestamps ...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
25,66388,Bump actions/setup-node from 6.4.0 to 7.0.0,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
26,66387,Bump github/codeql-action/init from 4.37.0 to ...,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
27,66386,Bump github/codeql-action/analyze from 4.37.0 ...,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
28,66385,Bump pypa/gh-action-pypi-publish from 1.14.0 t...,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
29,66384,Bump actions/setup-python from 6.3.0 to 7.0.0,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open

In [29]:
import requests

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

data = response.json()

print(type(data))

KeyboardInterrupt:

In [ ]:
info=pd.DataFrame(data)
info.iloc[0:5,]

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [ ]:
address_df = pd.json_normalize(info["address"])

address_df.head()

,street,suite,city,zipcode,geo.lat,geo.lng
0,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496
1,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618
2,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653
3,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990
4,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342

## Interacing with Databases

In [ ]:
# Create database

import sqlite3

query="""
CREATE TABLE test
(
 a VARCHAR(20),
 b VARCHAR(20),
 c REAL,
 d INTEGER
);"""

con=sqlite3.connect('mydata.sqlite')
con.execute(query)

In [ ]:
data = [('jecob','US',1.25,6),
        ('yosho','korea',3.2,4),
        ('steve','sydney',1.4,5)]

stmt="INSERT INTO test VALUES(?,?,?,?)"
con.executemany(stmt,data)

In [ ]:
con.commit()

In [ ]:
cursor=con.execute('select * from test')
rows=cursor.fetchall()
rows

[('jecob', 'US', 1.25, 6),
 ('yosho', 'korea', 3.2, 4),
 ('steve', 'sydney', 1.4, 5)]

In [ ]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [ ]:
con.close()

In [ ]:
import pandas as pd
ddf=pd.DataFrame(rows,columns=[x[0] for x in cursor.description])
ddf

       a       b     c  d
0  jecob      US  1.25  6
1  yosho   korea  3.20  4
2  steve  sydney  1.40  5

## Pandas provides one function that does all of this internally.

In [30]:
con = sqlite3.connect("mydata.sqlite")

df = pd.read_sql_query("SELECT * FROM test", con)

df

       a       b     c  d
0  jecob      US  1.25  6
1  yosho   korea  3.20  4
2  steve  sydney  1.40  5

In [33]:
import sys
print(sys.executable)

c:\Users\Dipak\Desktop\z_pandas\env_numpy\Scripts\python.exe

In [35]:
import sqlalchemy as sqla
db=sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test',db)

       a       b     c  d
0  jecob      US  1.25  6
1  yosho   korea  3.20  4
2  steve  sydney  1.40  5