## Detecting and Filtering Outliers

In [1]:
import numpy as np
import pandas as pd


nd=pd.DataFrame(np.random.randn(100,4))
nd

           0         1         2         3
0   1.486691  0.147203 -2.128011 -0.361675
1   1.475481 -1.967306 -1.629551  0.569608
2  -0.671202  0.996237 -0.047531  1.225722
3   0.643959  1.883262 -0.794072 -1.519035
4  -0.342710  0.062617 -0.247643  0.077683
..       ...       ...       ...       ...
95 -1.220683 -0.225106  0.292384 -1.719336
96  0.995684 -0.637319 -2.004297 -0.044042
97 -0.179991 -0.018475  1.451449  1.102614
98 -3.435236  1.470360 -0.726388  0.090949
99 -2.244400 -0.644387  0.252308  0.234423

[100 rows x 4 columns]

## Goal : remove outliers and keep values between(2 and-2)

In [2]:
nd.describe()

                0           1           2           3
count  100.000000  100.000000  100.000000  100.000000
mean    -0.131458    0.123950    0.029245    0.010624
std      1.162475    1.069608    1.005660    1.117479
min     -3.435236   -3.150815   -2.220915   -2.343405
25%     -0.885818   -0.599187   -0.704390   -0.724295
50%     -0.199588    0.050758    0.097548    0.047722
75%      0.719216    0.936714    0.730898    0.686584
max      2.541488    3.350096    2.170394    3.010622

In [3]:
col=nd[1]
col[np.abs(col)>2]

21    3.350096
36   -3.150815
Name: 1, dtype: float64

In [4]:
# To select all rows having a value exceedind 2 or -2 
nd[(np.abs(nd) > 2).any(axis=1) ]

           0         1         2         3
0   1.486691  0.147203 -2.128011 -0.361675
11 -0.007670 -0.243384 -0.765060  2.775511
18  1.355672  0.838439  1.027305 -2.278003
21  1.021173  3.350096 -2.061359 -1.439861
22  2.541488 -0.205510 -0.513022  1.825755
31 -2.263707 -0.201125 -2.220915  0.699529
34 -0.651928 -1.122048 -2.055944  1.116976
35 -2.018965 -0.438291  0.085863  0.058278
36 -1.711028 -3.150815 -0.757214 -0.404987
42 -0.752360  0.676995  0.589218  2.106199
50 -1.810833  0.365591  0.604585  3.010622
62 -2.016609  1.255973  0.528118 -0.518478
67  1.606457 -0.609225  0.146127 -2.343405
71  1.895211 -0.859776  2.170394  2.103111
76  0.711469 -0.715038  2.061866  0.147642
79 -2.385507  1.442012 -0.344852  0.385933
96  0.995684 -0.637319 -2.004297 -0.044042
98 -3.435236  1.470360 -0.726388  0.090949
99 -2.244400 -0.644387  0.252308  0.234423

In [5]:
nd[(np.abs(nd)>2)] = np.sign(nd) * 2
nd.describe()

                0           1           2           3
count  100.000000  100.000000  100.000000  100.000000
mean    -0.113228    0.121958    0.031628   -0.003116
std      1.100846    1.005843    0.990833    1.060447
min     -2.000000   -2.000000   -2.000000   -2.000000
25%     -0.885818   -0.599187   -0.704390   -0.724295
50%     -0.199588    0.050758    0.097548    0.047722
75%      0.719216    0.936714    0.730898    0.686584
max      2.000000    2.000000    2.000000    2.000000

In [6]:
np.sign(nd).head()

     0    1    2    3
0  1.0  1.0 -1.0 -1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0 -1.0  1.0
3  1.0  1.0 -1.0 -1.0
4 -1.0  1.0 -1.0  1.0

## Permutation and Random Sampling

`A permutation is an arrangement of objects where the order matters.`

In [7]:
df=pd.DataFrame(np.arange(5 * 4).reshape((5,4)))
df

sampler=np.random.permutation(5)
sampler

array([0, 4, 2, 3, 1], dtype=int32)

In [8]:
#  take function is equivalent iloc based indexing  
df.take(sampler)

    0   1   2   3
0   0   1   2   3
4  16  17  18  19
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [9]:
df.sample(n=3)

    0   1   2   3
2   8   9  10  11
1   4   5   6   7
4  16  17  18  19

`np.random.permutation()` → Shuffle all elements exactly once.<br>
`Series.sample(replace=True)` → Randomly pick elements; duplicates are allowed.<br>
`Series.sample(replace=False)` → Randomly pick without duplicates.

In [10]:
# The logic of this code is: indices are randomly sampled from 0 (to len(choice) - 1) with replacement,
#  and the corresponding values are selected from choice. The resulting Series has a length of 8.
choice=pd.Series([5,7,-1,6,4])

draws=choice.sample(n=10,replace=True)
draws

1    7
0    5
4    4
0    5
3    6
0    5
2   -1
1    7
2   -1
2   -1
dtype: int64

## Computing Indicator / Dummy Variables

In [11]:
df=pd.DataFrame({ 
    'name':['kiran','lornange','Halland','yamal','Jics','Hileo','catq'],
    'class':['c1','c3','c1','c2','c2','c1','c3']

       })
df

       name class
0     kiran    c1
1  lornange    c3
2   Halland    c1
3     yamal    c2
4      Jics    c2
5     Hileo    c1
6      catq    c3

In [12]:
print(pd.get_dummies(df['class']))
print(pd.get_dummies(df['class']   , dtype=int) )

      c1     c2     c3
0   True  False  False
1  False  False   True
2   True  False  False
3  False   True  False
4  False   True  False
5   True  False  False
6  False  False   True
   c1  c2  c3
0   1   0   0
1   0   0   1
2   1   0   0
3   0   1   0
4   0   1   0
5   1   0   0
6   0   0   1

In [13]:
dum=pd.get_dummies(df['class'],prefix='class')
df_with_dum=df[['name']].join(dum)
df_with_dum

       name  class_c1  class_c2  class_c3
0     kiran      True     False     False
1  lornange     False     False      True
2   Halland      True     False     False
3     yamal     False      True     False
4      Jics     False      True     False
5     Hileo      True     False     False
6      catq     False     False      True

In [14]:
mn=['movie_id','title','genres']
movies=pd.read_table('datasets/movies.dat',sep='::',header=None,names=mn,engine='python',
                     encoding='latin1')
movies.head(10)

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [15]:
all_genres=[]
for x in movies.genres:
    all_genres.extend(x.split('|'))

genres=pd.Series(all_genres).unique()
genres

<StringArray>
[  'Animation',  'Children's',      'Comedy',   'Adventure',     'Fantasy',
     'Romance',       'Drama',      'Action',       'Crime',    'Thriller',
      'Horror',      'Sci-Fi', 'Documentary',         'War',     'Musical',
     'Mystery',   'Film-Noir',     'Western']
Length: 18, dtype: str

* For construct the indicator DF : first step--> DF with all zeros

In [16]:

zero_matrix = np.zeros((len(movies), len(genres)))

dummies = pd.DataFrame(zero_matrix, columns=genres)

In [17]:
gen=movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [18]:
# It will be find the index of gen.split() in dummies . 
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [19]:
for i, gen in enumerate(movies.genres):
    indices=dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices]=1
    # set the value=1 through iloc

In [20]:
movies_windic=movies.join(dummies.add_prefix('Genre__'))
movies_windic.iloc[0]

movie_id                                        1
title                            Toy Story (1995)
genres                Animation|Children's|Comedy
Genre__Animation                              1.0
Genre__Children's                             1.0
Genre__Comedy                                 1.0
Genre__Adventure                              0.0
Genre__Fantasy                                0.0
Genre__Romance                                0.0
Genre__Drama                                  0.0
Genre__Action                                 0.0
Genre__Crime                                  0.0
Genre__Thriller                               0.0
Genre__Horror                                 0.0
Genre__Sci-Fi                                 0.0
Genre__Documentary                            0.0
Genre__War                                    0.0
Genre__Musical                                0.0
Genre__Mystery                                0.0
Genre__Film-Noir                              0.0
Genre__Western                                0.0
Name: 0, dtype: object

### A useful techinque for statistical applications is to combine `get_dummies` with a discretization function like ` cut`:

In [21]:
np.random.seed(42)
values=np.random.rand(10)
values

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [22]:
bins=[0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins),dtype=int)

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           1           0           0           0
1           0           0           0           0           1
2           0           0           0           1           0
3           0           0           1           0           0
4           1           0           0           0           0
5           1           0           0           0           0
6           1           0           0           0           0
7           0           0           0           0           1
8           0           0           0           1           0
9           0           0           0           1           0